package:
  name: climate4r
  version: 1.5.0

source:
  url: file://{{ RECIPE_DIR }}/install.R

requirements:
  build:
  - numpy
  - pandas
  - dask
  - iris

  - r-abind
  - r-akima
  - r-askpass
  - r-assertthat
  - r-backports
  - r-base>=3.6
  - r-base64enc
  - r-bitops
  - r-boot
  - r-brew
  - r-brio
  - r-cachem
  - r-callr
  - r-caret
  - r-circstats
  - r-class
  - r-cli
  - r-climdex.pcic
  - r-clipr
  - r-codetools
  - r-colorspace
  - r-commonmark
  - r-config
  - r-covr
  - r-crayon
  - r-credentials
  - r-crosstalk
  - r-curl
  - r-data.table
  - r-deepnet
  - r-deldir
  - r-desc
  - r-devtools
  - r-diffobj
  - r-digest
  - r-dismo
  - r-dotcall64
  - r-dplyr
  - r-dt
  - r-dtw
  - r-e1071
  - r-earth
  - r-easyverification
  - r-ellipsis
  - r-evaluate
  - r-evd
  - r-fansi
  - r-farver
  - r-fastmap
  - r-fields
  - r-foreach
  - r-formula
  - r-fs
  - r-gdalutils
  - r-generics
  - r-geosphere
  - r-gert
  - r-ggplot2
  - r-gh
  - r-git2r
  - r-gitcreds
  - r-glmnet
  - r-glue
  - r-goftest
  - r-gower
  - r-gridextra
  - r-gtable
  - r-gtools
  - r-highr
  - r-htmltools
  - r-htmlwidgets
  - r-httr
  - r-ini
  - r-ipred
  - r-isoband
  - r-iterators
  - r-jpeg
  - r-jsonlite
  - r-keras
  - r-kernsmooth
  - r-knitr
  - r-kohonen
  - r-labeling
  - r-later
  - r-lattice
  - r-latticeextra
  - r-lava
  - r-lazyeval
  - r-lifecycle
  - r-lmomco
  - r-lmoments
  - r-lpsolve
  - r-lubridate
  - r-magrittr
  - r-mapplots
  - r-maps
  - r-markdown
  - r-mass
  - r-matrix
  - r-memoise
  - r-mgcv
  - r-mime
  - r-modelmetrics
  - r-munsell
  - r-ncdf4
  - r-nlme
  - r-nnet
  - r-numderiv
  - r-openssl
  - r-padr
  - r-pbapply
  - r-pcict
  - r-pillar
  - r-pkgbuild
  - r-pkgconfig
  - r-pkgload
  - r-plotmo
  - r-plotrix
  - r-plyr
  - r-png
  - r-polyclip
  - r-praise
  - r-presenceabsence
  - r-prettyunits
  - r-proc
  - r-processx
  - r-prodlim
  - r-promises
  - r-proxy
  - r-ps
  - r-purrr
  - r-r.methodss3
  - r-r.oo
  - r-r.utils
  - r-r6
  - r-randomforest
  - r-ranger
  - r-rappdirs
  - r-raster
  - r-rcmdcheck
  - r-rcolorbrewer
  - r-rcpp
  - r-rcpparmadillo
  - r-rcppeigen
  - r-rcurl
  - r-recipes
  - r-rematch2
  - r-remotes
  - r-reshape2
  - r-reticulate
  - r-rex
  - r-rgdal
  - r-rjava
  - r-rlang
  - r-rmarkdown
  - r-roxygen2
  - r-rpart
  - r-rprojroot
  - r-rstudioapi
  - r-rversions
  - r-sampling
  - r-scales
  - r-sessioninfo
  - r-shape
  - r-signal
  - r-sm
  - r-sp
  - r-spam
  - r-spatstat
  - r-spatstat.core
  - r-spatstat.data
  - r-spatstat.geom
  - r-spatstat.linnet
  - r-spatstat.sparse
  - r-spatstat.utils
  - r-specsverification
  - r-spei
  - r-splancs
  - r-squarem
  - r-sticky
  - r-stringi
  - r-stringr
  - r-survival
  - r-sys
  - r-teachingdemos
  - r-tensor
  - r-tensorflow
  - r-testthat
  - r-tfruns
  - r-tibble
  - r-tidyr
  - r-tidyselect
  - r-timedate
  - r-tinytex
  - r-tree
  - r-udunits2
  - r-usethis
  - r-utf8
  - r-vctrs
  - r-verification
  - r-vioplot
  - r-viridis
  - r-viridislite
  - r-waldo
  - r-whisker
  - r-withr
  - r-xfun
  - r-xml2
  - r-xopen
  - r-yaml
  - r-zeallot
  - r-zip
  - r-zoo
  run:
  - numpy
  - pandas
  - dask
  - iris

  - r-abind
  - r-akima
  - r-askpass
  - r-assertthat
  - r-backports
  - r-base>=3.6
  - r-base64enc
  - r-bitops
  - r-boot
  - r-brew
  - r-brio
  - r-cachem
  - r-callr
  - r-caret
  - r-circstats
  - r-class
  - r-cli
  - r-climdex.pcic
  - r-clipr
  - r-codetools
  - r-colorspace
  - r-commonmark
  - r-config
  - r-covr
  - r-crayon
  - r-credentials
  - r-crosstalk
  - r-curl
  - r-data.table
  - r-deepnet
  - r-deldir
  - r-desc
  - r-devtools
  - r-diffobj
  - r-digest
  - r-dismo
  - r-dotcall64
  - r-dplyr
  - r-dt
  - r-dtw
  - r-e1071
  - r-earth
  - r-easyverification
  - r-ellipsis
  - r-evaluate
  - r-evd
  - r-fansi
  - r-farver
  - r-fastmap
  - r-fields
  - r-foreach
  - r-formula
  - r-fs
  - r-gdalutils
  - r-generics
  - r-geosphere
  - r-gert
  - r-ggplot2
  - r-gh
  - r-git2r
  - r-gitcreds
  - r-glmnet
  - r-glue
  - r-goftest
  - r-gower
  - r-gridextra
  - r-gtable
  - r-gtools
  - r-highr
  - r-htmltools
  - r-htmlwidgets
  - r-httr
  - r-ini
  - r-ipred
  - r-isoband
  - r-iterators
  - r-jpeg
  - r-jsonlite
  - r-keras
  - r-kernsmooth
  - r-knitr
  - r-kohonen
  - r-labeling
  - r-later
  - r-lattice
  - r-latticeextra
  - r-lava
  - r-lazyeval
  - r-lifecycle
  - r-lmomco
  - r-lmoments
  - r-lpsolve
  - r-lubridate
  - r-magrittr
  - r-mapplots
  - r-maps
  - r-markdown
  - r-mass
  - r-matrix
  - r-memoise
  - r-mgcv
  - r-mime
  - r-modelmetrics
  - r-munsell
  - r-ncdf4
  - r-nlme
  - r-nnet
  - r-numderiv
  - r-openssl
  - r-padr
  - r-pbapply
  - r-pcict
  - r-pillar
  - r-pkgbuild
  - r-pkgconfig
  - r-pkgload
  - r-plotmo
  - r-plotrix
  - r-plyr
  - r-png
  - r-polyclip
  - r-praise
  - r-presenceabsence
  - r-prettyunits
  - r-proc
  - r-processx
  - r-prodlim
  - r-promises
  - r-proxy
  - r-ps
  - r-purrr
  - r-r.methodss3
  - r-r.oo
  - r-r.utils
  - r-r6
  - r-randomforest
  - r-ranger
  - r-rappdirs
  - r-raster
  - r-rcmdcheck
  - r-rcolorbrewer
  - r-rcpp
  - r-rcpparmadillo
  - r-rcppeigen
  - r-rcurl
  - r-recipes
  - r-rematch2
  - r-remotes
  - r-reshape2
  - r-reticulate
  - r-rex
  - r-rgdal
  - r-rjava
  - r-rlang
  - r-rmarkdown
  - r-roxygen2
  - r-rpart
  - r-rprojroot
  - r-rstudioapi
  - r-rversions
  - r-sampling
  - r-scales
  - r-sessioninfo
  - r-shape
  - r-signal
  - r-sm
  - r-sp
  - r-spam
  - r-spatstat
  - r-spatstat.core
  - r-spatstat.data
  - r-spatstat.geom
  - r-spatstat.linnet
  - r-spatstat.sparse
  - r-spatstat.utils
  - r-specsverification
  - r-spei
  - r-splancs
  - r-squarem
  - r-sticky
  - r-stringi
  - r-stringr
  - r-survival
  - r-sys
  - r-teachingdemos
  - r-tensor
  - r-tensorflow
  - r-testthat
  - r-tfruns
  - r-tibble
  - r-tidyr
  - r-tidyselect
  - r-timedate
  - r-tinytex
  - r-tree
  - r-udunits2
  - r-usethis
  - r-utf8
  - r-vctrs
  - r-verification
  - r-vioplot
  - r-viridis
  - r-viridislite
  - r-waldo
  - r-whisker
  - r-withr
  - r-xfun
  - r-xml2
  - r-xopen
  - r-yaml
  - r-zeallot
  - r-zip
  - r-zoo

about:
  home: https://github.com/SantanderMetGroup/climate4R
