package:
  name: climate4r
  version: 1.5.1

source:
  url: file://{{ RECIPE_DIR }}/install.R

requirements:
  build:
  - iris

  - r-base>=3.6
  - r-caret
  - r-dismo
  - r-padr
  - r-presenceabsence
  - r-deepnet
  - r-splancs
  - r-gtools
  - r-spei
  - r-tree
  - r-rmarkdown
  - r-devtools
  - r-sampling
  - r-geosphere
  - r-randomforest
  - r-keras
  - r-rcurl
  - r-e1071
  - r-mapplots
  - r-vioplot
  - r-akima
  - r-ncdf4
  - r-glmnet
  - r-latticeextra
  - r-rjava
  - r-sticky
  - r-verification
  - r-udunits2
  - r-easyverification
  - r-kohonen
  - r-ranger
  - r-climdex.pcic
  - r-gdalutils
  - r-evd
  - r-signal
  - r-earth
  - "r-spatstat<2"
  - "r-spatstat.linnet<2"

  run:
  - iris

  - r-base>=3.6
  - r-caret
  - r-dismo
  - r-padr
  - r-presenceabsence
  - r-deepnet
  - r-splancs
  - r-gtools
  - r-spei
  - r-tree
  - r-rmarkdown
  - r-devtools
  - r-sampling
  - r-geosphere
  - r-randomforest
  - r-keras
  - r-rcurl
  - r-e1071
  - r-mapplots
  - r-vioplot
  - r-akima
  - r-ncdf4
  - r-glmnet
  - r-latticeextra
  - r-rjava
  - r-sticky
  - r-verification
  - r-udunits2
  - r-easyverification
  - r-kohonen
  - r-ranger
  - r-climdex.pcic
  - r-gdalutils
  - r-evd
  - r-signal
  - r-earth
  - "r-spatstat<2"
  - "r-spatstat.linnet<2"

about:
  home: https://github.com/SantanderMetGroup/climate4R
